name: Golfpost Marcel Schneider Monitor Discord

on:
  schedule:
    # Alle zwei Stunden zwischen 7 und 21 Uhr deutscher Zeit, entspricht 5–19 UTC
    - cron: "0 5-19/2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser

      - name: Feed prüfen und auf Discord posten
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python rss_monitor_discord.py

      - name: Zustand committen falls geändert
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add known_ids.json .etag .lastmod || true
            git commit -m "Update feed state"
            git push
          fi
