name: Golfpost Marcel Schneider Monitor

on:
  schedule:
    - cron: "*/30 * * * *"   # alle 30 Minuten
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser

      - name: Fetch and notify
        env:
          TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
        run: |
          python rss_monitor.py

      - name: Commit state if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add known_ids.json .etag .lastmod || true
            git commit -m "Update feed state"
            git push
          fi
